server:
  port: 8090

chatbot-api:
  cookie: "receive-cookie-deprecation=1; lang=zh-cn; _uab_collina=171273651984528152675161; _yuque_session=jK7lMKFZjjeZOJbSP_HaXxtNj3rKtEszODgJcR3IfrJ7aAFj9B_FYCmBfS4dH-zt27_-1YPNlDqi6nlTAn8_BQ==; tfstk=fbOZsRNJnfhZCBJcYM1VYNTTZT1Oi_nS_IsfoEYc5Gjg15ZDLFTP5Rg9oi-2AMCffC963Pde4SNsXAL0gs1mV0GSNFUOMsmWJFS0slQlylcfmGYhgMDs10GSNFDGWsTnVqHMVCsAosbGnsfn8a7ViSbMmMXhraZGisxD-27Vo52GIt23-NGPGKpu5Z6iX1-DScgIp9skSGY6zBD5CRLdYJyeTdBNqjSUiSAF7eQfugPrhgvRfTsJxXNNgeb2YT9Z45-2oUpcLIri53YDXB5OaxgOUpvBFOJEjSSB1ZWli9z0ie5DItAVZbqFJpY6nCKauSb91Q6V29u0Mt1HNTvkbr3J-1bDDTdj25IMoUdJF_la2NJHz6SrnoQn-cAvQo2VIwQFV2u3FqNWyrPQSLeYHOnh8ggG9-eAIwQFV2uUH-B9KwSSS6C..; yuque_ctoken=hf1ufn4x60v1ih06obgr0mhxlukqaaf7; current_theme=default; aliyungf_tc=c3a9b4f26c035f52da729d7f8be1ea4b33dcf827a7e7f4ea063667bf7a938be1; acw_tc=ac11000117174716467932967e4d7d7c09a7c784630c3b6b251230e16b86cf"
  commentable_id: 169484218

openai:
  API_URL: "https://api.openai.com/v1/chat/completions"
  API_KEY: "${xxxxax}"
